config/routes.rb
Leave::Application.routes.draw do

  resources :roles

  resources :admin, :only => [:index], :controller => :admin
  namespace :admin do   
  resources :employees do
   collection do
        get 'search'
        get 'export_to_csv' => :export_to_csv 
        
      end   
  end
  resources :locations
  resources :leave_requests
  resources :leaves
controller :leave_requests do
    get 'request_leave' => :new
    get 'request_success' => :request_success
    get 'leave_request_search' =>:index
    get 'request_update' =>   :request_update
    get 'employee_leaves' =>   :index
    get 'applied_leaves' =>   :applied_leaves
    get 'leave_cancel' =>   :leave_cancel
    get 'leave_approve' =>   :leave_approve
    post 'leave_approve_update' =>   :leave_approve_update
    get 'commit_leave' =>   :commit_leave
    post 'leave_request_commit' =>   :leave_request_commit
    get 'forcedleave' =>   :forcedleave
    get 'addforcedleave' =>   :addforcedleave
    post 'addforcedleave' =>   :addforcedleave
  

    

  end

  resources :high_scores    
  end

  resources :leaves
  resources :employees 
  resources :leave_requests
 
  get 'change_password' => 'sessions#change_password'
  post 'change_update' => 'sessions#change_update'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  controller :leave_requests do
    get 'request_leave' => :new
    get 'request_success' => :request_success
    get 'leave_request_search' =>:index
    get 'request_update' =>   :request_update
    get 'employee_leaves' =>   :employee_leaves
    get 'leave_cancel' =>   :leave_cancel
    get 'leave_approve' =>   :leave_approve
    post 'leave_approve_update' =>   :leave_approve_update

  end

  root :to => 'sessions#new'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :address, :contact_no, :created_by, :email, :first_name, :last_name, :manager_id, :modified_by, :empid, :password_digest, :password, :location_id, :password_confirmation
                :leafe_attributes
  validates :email, presence: true, uniqueness: true
  validates :empid, presence: true, uniqueness: true

  has_secure_password

  has_many :leave_requests , :dependent => :destroy
  has_many :employee_roles, :class_name => "EmployeesRoles"  ,:dependent => :destroy 
  has_and_belongs_to_many :roles 
  has_one :leafe  , :dependent => :destroy
  
  accepts_nested_attributes_for :leafe 

def self.monthlyupdates       
  	
        @leave=Leafe.all        
        @leave.each do |leafe| 
        @l=Leafe.find(leafe.id)
      
           @leaves_audit_logs = LeavesAuditLog.new
           @leaves_audit_logs.preels=leafe.els
	   @leaves_audit_logs.prenels=leafe.nels
	   @leaves_audit_logs.prelops=leafe.lops
	   @leaves_audit_logs.precompoffs=leafe.compoffs
	   @leaves_audit_logs.employee_id=leafe.employee_id
           @l.els=leafe.els+1
           @l.nels=leafe.nels+1
	   @leaves_audit_logs.currentels=@l.els
	   @leaves_audit_logs.currentnels=@l.nels
	   @leaves_audit_logs.currentlops=@l.lops
	   @leaves_audit_logs.currentcompoffs=@l.compoffs	  
	   @leaves_audit_logs.tableorscreen='cronjob generalLeave'
           @leaves_audit_logs.save
	   @l.update_attributes(:id =>leafe.id)
end


end


def as_xls(options = {})
  {
      "Empid" => empid,
      "Name" => first_name+" "+last_name,
      "E-Mail" => email,
      "Address" => address,
      "Contact NO" => contact_no,
      "ELs" => els,
      "NELs" => nels,
      "LOPs" => lops,
      "COMPOFFs" => compoffs,
	     
    
  }
end



end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < AdminController
require 'csv'
include ActionView::Helpers::NumberHelper

def index
   @page_title='Employess'
   @search=" employee_id >0 "
   if session[:roles].include?(4) == false
   @search+=" AND employees.location_id = '#{session[:location_id]}'"
   end 
   if params[:empid].present?
      @search+=" AND empid LIKE '%#{params[:empid]}%'"
    end
   
    if params[:first_name].present?
      @search+=" AND (first_name LIKE '%#{params[:first_name]}%' OR  last_name LIKE '%#{params[:first_name]}%')"
    end
    
    @employees = Leafe.joins(:employee).where(@search).paginate(:page => params[:page],:per_page => 10).order("employees.empid ASC")


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
      
    end
  end
# GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])
  end


  # GET /employees/new
  # GET /employees/new.json
  def new
   @page_title='Add Employee'
   @employee = Employee.new
   @heading="Add Employee"   
   if session[:roles].include?(4)
    @locations = Admin::Location.all
    @roles = Role.all
   else
     @locations = Admin::Location.where("id= ?", session[:location_id])
     @roles = Role.where("id!=4")
   end
  
   #raise @locations.inspect
   @manager_list=Employee.joins(:employee_roles).where('employees_roles.role_id=3').order('first_name ASC');
   @role_user_ids =EmployeesRoles.where(:employee_id=>params[:id]).select("role_id")
   @condition={} 

   respond_to do |format|
      format.html # manager.html.erb
      format.json { render json: @employee }
    end

  end

  # GET /employees/1/edit
  def edit
  @page_title='Edit Employee'
  @employee= Employee.find(params[:id])
  @heading="Edit Employee Details"
   if session[:roles].include?(4)
    @locations = Admin::Location.all
    @roles = Role.all
   else
     @locations = Admin::Location.where("id= ?", session[:location_id])
     @roles = Role.where("id!=4")
   end
  @manager_list=Employee.joins(:employee_roles).where('employees_roles.role_id=3').order('first_name ASC');
  @conditions =EmployeesRoles.where(:employee_id=>params[:id]).select("role_id")
  @condition={}   
  @conditions.each do |role|  
  @condition[role.role_id] = role.role_id  
  end
  end

  # POST /employees
  # POST /employees.json
  def create
 @employee = Employee.new(params[:employee])
 @roles= Role.all
 @locations = Admin::Location.all
 @manager_list=Employee.joins(:employee_roles).where('employees_roles.role_id=3');
 @employee.location_id= params[:location_id]
 @employee.manager_id= params[:manager_id]
 @conditions =EmployeesRoles.where(:employee_id=>params[:id]).select("role_id")
 @condition={}   
 @conditions.each do |role|  
 @condition[role.role_id] = role.role_id
 end 

    respond_to do |format|
      if @employee.save
        Leafe.create(:employee_id => @employee.id)
        params[:roles_ids].each do |role_id|
        EmployeesRoles.create(:role_id => role_id, :employee_id => @employee.id, :createdby =>session[:user_id], :modifiedby=>session[:user_id])
        end   
        UserMailer.registration_email(@employee,'Login details',@employee.email).deliver       
        format.html { redirect_to admin_employees_path, notice: 'Employee was successfully created.' }
        format.json { render json: admin_employees_path, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: admin_employee_path.errors, status: :unprocessable_entity }
      end
    end
  
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update  
  @employee = Employee.find(params[:id])
  @employee.location_id= params[:location_id]
  @employee.manager_id= params[:manager_id]
  @roles= Role.all
  @locations = Admin::Location.all
  @manager_list=Employee.joins(:employee_roles).where('employees_roles.role_id=3');
    respond_to do |format|
      if @employee.update_attributes(params[:employee])      
    EmployeesRoles.delete_all(:employee_id =>@employee.id)
  params[:roles_ids].each do |role_id|
        EmployeesRoles.create(:role_id => role_id, :employee_id => @employee.id, :createdby =>session[:user_id], :modifiedby=>session[:user_id])
        end

        format.html { redirect_to edit_admin_employee_path(params[:id]), notice: 'Employee details saved successfully' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  
  end

  # DELETE /employees/1
  # DELETE /employees/1.json


  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to admin_employees_path

  
  end

def export_to_csv   

 @users = Employee.joins(:leafe).select("employees.empid,employees.first_name,employees.last_name,employees.email,employees.contact_no,employees.address,leaves.els,leaves.nels,leaves.lops,leaves.compoffs").order("empid ASC").find(:all)
 

 #raise @users.inspect 
 #raise @u.inspect  
time = Time.new
send_data @users.to_xls, content_type: 'application/vnd.ms-excel', filename: "Employesse#{time.strftime("%d-%m-%Y %I:%M:%S %p")}.xls" 


=begin    
    @users = Employee.order("empid ASC").find(:all)
    csv_string = CSV.generate(:col_sep => "\t") do |csv|        
         csv << ["Empid", "First Name", "Last name","Contact No",'Address',"Email",'ELs','NELs','CompOffs','LOPs']
         @users.each do |user|
           csv << [user.empid, user.first_name, user.last_name,user.contact_no,user.address,user.email,number_to_human(user.leafe.els),number_to_human(user.leafe.nels),number_to_human(user.leafe.compoffs),number_to_human(user.leafe.lops)]
         end
    end     
    
  time = Time.new
   send_data csv_string,:type => 'text/csv; charset=iso-8859-1; header=present',:disposition => "attachment; filename=employee#{time.strftime("%d-%m-%Y %I:%M:%S %p")}.csv" 
=end

end 






end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  before_filter :authorize


  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Leave.new

    respond_to do |format|
      format.html # manager.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/admin/employees/_form.html.erb
<section id="body">
  <div class="container">
    <div class="col12">
   <%= form_for @employee , :url =>  @employee.new_record? ? admin_employees_path: admin_employee_path,html: {id: 'employee',name:'employee'}  do |f| %>
    		 <table class="table2 width_full" style="border:solid 1px #0d5478;">
			
			
			 
				<tr>
                	<td>
                    	<table align="center">
                        	<tr>
                         <td colspan="2" align="center">
	                  <h1><%= @heading %></h1>
                         </td></tr>
	              <%  if @employee.errors.any? %>
			<tr>
                        <td colspan="2" align="center">
			  <div id="error_explanation">
			      <ul>
			      <% @employee.errors.full_messages.each do |msg| %>
				<li style="color:red;"><%= msg %></li>
			      <% end %>
			      </ul>
			    </div></td>			
			</tr>
                         <% end %>

				<% if flash[:notice] %>
			<tr>
                        <td colspan="2" align="center"><h1><%= flash[:notice] %> </h1></td>			
			</tr>
                         <% end %>
                             <tr>       
                              <td valign="top"><%= f.label :'Employee ID:' %></td>
                              <td><%= f.text_field :empid ,:class => 'required'%></td>
                            </tr>
                            <tr>
                              <td valign="top"><%= f.label :'First Name:' %></td>
                              <td><%= f.text_field :first_name ,:class => 'required'%></td>
                            </tr>
                             <tr>
                              <td valign="top"><%= f.label :'Last Name:' %></td>
                              <td><%= f.text_field :last_name ,:class => 'required'%></td>
                            </tr>
                            
                            <tr>
                              <td valign="top"><%= f.label :'Email:' %></td>
                              <td><%= f.text_field :email ,:class => 'required'%></td>
                            </tr>
                           <tr>
                              <td valign="top"><%= f.label :'Contact No:' %></td>
                              <td><%= f.text_field :contact_no ,:class => 'required'%></td>					
                            </tr>
                            <tr>
                              <td valign="top"><%= f.label :'Address:' %></td>
                              <td><%= f.text_area :address ,:class => 'required'%>
                              
                              <% if @employee.id.blank? %>
                              <%= f.hidden_field :password ,:value=>'logictree' %>
                              <%= f.hidden_field :password_confirmation ,:value=>'logictree' %>
                              <% end %>
                             </td>
                            </tr>
	                     <tr>
                              <td valign="top"><%= f.label :'Role:' %></td>
                              <td>
                              <% @roles.each do |role| %>
			     
				<%= check_box_tag "roles_ids[]",  role.id , @condition.include?(role.id) || role.id==2 ? true : false %>
				<%=  role.title -%>			      
			        <% end %>
                                </td>					
                            </tr>
                             <tr>
                              <td valign="top"><%= f.label :'Location:' %></td>
                              <td> 
 

                <%= select_tag(:location_id, options_from_collection_for_select(@locations, :id, :title , params[:location_id] ||  @employee.location_id)) %>
                            
                               </td>					
                            </tr>
                            
			      <tr>
			      <td valign="top"> <%= f.label :"Manager" %></td>
			      <td>
                            <% cities_array = @manager_list.all.map { |employee| [employee.first_name.capitalize+' '+employee.last_name.capitalize, employee.id] } %>
<%= select_tag(:manager_id,  options_for_select(cities_array , params[:manager_id] ||  @employee.manager_id) ) %>
			      </td>
				
			     </tr> 
                             
                           
                           
                            <tr>
                              <td>&nbsp;</td>
                              <td><%= f.submit 'Submit',:class=>'button' %></td>
                            </tr>                            
                        </table>
                    </td>
                </tr>
				
				
              </table>  
					
<% end %>
    </div>
  </div>
</section>
<script type="text/javascript"> 
	$(document).ready(function(){ 
         $.validator.messages.required = '';

		$("#employee").validate({
		 rules: {
			role: {
				required: true,
				minlength:1,
			}
		 } 
		}); 
	}); 
</script>

app/views/admin/employees/edit.html.erb
<%= render 'form' %>

app/views/admin/employees/export_to_csv.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Last name</th>
    <th>First name</th>
    <th>Contact no</th>
    <th>Address</th>
    <th>Email</th>
    <th>Password</th>
    <th>Manager</th>
    <th>Createdby</th>
    <th>Modifiedby</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.last_name %></td>
    <td><%= employee.first_name %></td>
    <td><%= employee.contact_no %></td>
    <td><%= employee.address %></td>
    <td><%= employee.email %></td>
    <td><%= employee.password %></td>
    <td><%= employee.manager_id %></td>
    <td><%= employee.createdby %></td>
    <td><%= employee.modifiedby %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/admin/employees/index.html.erb
<section id="body">
  <div class="container">
    <div class="col12">

    	<table class="width_full" style="border:solid 1px #0d5478;">
         
<tr>
            	<td>
 <%= form_tag  admin_employees_path , :method => :get do %>
                    <table align="center">
                      <tr><td align="center"><h1>Search Employees</h1></td></tr>
                      <tr><td>
<%= label_tag :empid, 'By Emp ID:' %> <%= text_field_tag :empid, params[:empid] %> <%= label_tag :first_name, ' / Name:' %>
                <%= text_field_tag :first_name, params[:first_name] %>

</td></tr>				  
                      <tr><td align="center"><%= submit_tag 'Submit',:class=>'button' %></td></tr>
                    </table> 
  <% end %>               
                </td>
                <td align="right">

   <table width="75%" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td align="right"><%= link_to (image_tag "xls.png", :title => 'Import'),export_to_csv_admin_employees_path(:format=>"xls")%></td>
	<td align="right"><%= link_to "Add Employee", new_admin_employee_path, :class => "button" %></td>
</tr>
</table>  


              
     

                	
                </td>
            </tr>	
            <tr>
            	<td colspan="2">
                	
		<table class="table1 width_full">
				  <tbody>
                  <tr>
                  	<td rowspan="2" align="center"><strong>Emp ID</strong></td>
                    <td rowspan="2" align="center"><strong>Name</strong></td>
                    <th colspan="2">Available</th>
                    <th colspan="2">Incurred</th>
                    <th rowspan="2" align="center"><strong>Options</strong></th>
                  </tr>
                  <tr>
		 <th>ELs</th>
                 <th>NELs</th>	
		 <th>LOPs</th>
                 <th>Comp Offs</th>						
		 </tr>
				  <% @employees.each do |employee| %>
				
				  <tr>
					<td height="30px;"><%= employee.employee.empid %></td>
					<td><%= employee.employee.first_name.capitalize+" "+employee.employee.last_name.capitalize %></td>
					<td><%= number_to_human(employee.els) %></td>
					<td><%= number_to_human(employee.nels) %></td>
					<td><%= number_to_human(employee.lops) %></td>
					<td><%= number_to_human(employee.compoffs) %></td>
					<td>
                                        <%= link_to 'View/Edit Details', edit_admin_employee_path(employee.employee_id), :class=>'button' %>
					<%= link_to 'View Applied Leaves', admin_applied_leaves_path(:id=>employee.employee_id), :class=>'button' %>
					<%= link_to 'Edit Leaves', edit_admin_leafe_path(employee.employee_id), :class=>'button' %>
                                        <%= link_to 'Delete', admin_employee_path(employee.employee_id), method: :delete, data: { confirm: 'Are you sure?' }, :class=>'button' %>
                                       </td>
				  </tr>	
	<% end %>                
				<%  if @employees.count>10 %>
				<tr>
				  <td colspan="7" align="center">
				    <%= will_paginate @employees, renderer: BootstrapPagination::Rails %>                    
				  </td>
				</tr>
				<% end %>
				<% if @employees.empty? %>
				<tr>
				  <td colspan="7" align="center">No Records Found</td>
				</tr>
				<% end %>

				

				 
				</tbody></table>                	
                </td>
            </tr>
        </table>	

    
    </div>
  </div>
</section>

app/views/admin/employees/new.html.erb
<%= render 'form' %>

app/views/admin/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Last name:</b>
  <%= @employee.last_name %>
</p>

<p>
  <b>First name:</b>
  <%= @employee.first_name %>
</p>

<p>
  <b>Contact no:</b>
  <%= @employee.contact_no %>
</p>

<p>
  <b>Address:</b>
  <%= @employee.address %>
</p>

<p>
  <b>Email:</b>
  <%= @employee.email %>
</p>

<p>
  <b>Password:</b>
  <%= @employee.password %>
</p>

<p>
  <b>Manager:</b>
  <%= @employee.manager_id %>
</p>

<p>
  <b>Createdby:</b>
  <%= @employee.createdby %>
</p>

<p>
  <b>Modifiedby:</b>
  <%= @employee.modifiedby %>
</p>


<%= link_to 'Edit', edit_admin_employee_path(@employee) %> |
<%= link_to 'Back', admin_employees_path %>