config/routes.rb
Leave::Application.routes.draw do

  resources :roles

  resources :admin, :only => [:index], :controller => :admin
  namespace :admin do   
  resources :employees do
   collection do
        get 'search'
        get 'export_to_csv' => :export_to_csv 
        
      end   
  end
  resources :locations
  resources :leave_requests
  resources :leaves
controller :leave_requests do
    get 'request_leave' => :new
    get 'request_success' => :request_success
    get 'leave_request_search' =>:index
    get 'request_update' =>   :request_update
    get 'employee_leaves' =>   :index
    get 'applied_leaves' =>   :applied_leaves
    get 'leave_cancel' =>   :leave_cancel
    get 'leave_approve' =>   :leave_approve
    post 'leave_approve_update' =>   :leave_approve_update
    get 'commit_leave' =>   :commit_leave
    post 'leave_request_commit' =>   :leave_request_commit
    get 'forcedleave' =>   :forcedleave
    get 'addforcedleave' =>   :addforcedleave
    post 'addforcedleave' =>   :addforcedleave
  

    

  end

  resources :high_scores    
  end

  resources :leaves
  resources :employees 
  resources :leave_requests
 
  get 'change_password' => 'sessions#change_password'
  post 'change_update' => 'sessions#change_update'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  controller :leave_requests do
    get 'request_leave' => :new
    get 'request_success' => :request_success
    get 'leave_request_search' =>:index
    get 'request_update' =>   :request_update
    get 'employee_leaves' =>   :employee_leaves
    get 'leave_cancel' =>   :leave_cancel
    get 'leave_approve' =>   :leave_approve
    post 'leave_approve_update' =>   :leave_approve_update

  end

  root :to => 'sessions#new'

end

app/models/leave_request.rb
class LeaveRequest < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :address, :contactno, :createdby, :currentproject, :employee_id, :fromdate, :managerid, :modifiedby, :numdays, :reason, :remarks, :resumeon, :todate
                :leafe_attributes

 belongs_to :employee
 has_many :processed_leave , :class_name => "ProcessedLeave"

def self.els_count
    sum(:els)
  end

  def self.nels_count
    sum(:nels)
  end

  def self.lops_count
    sum(:lops)
  end

  def self.compoffs_count
    sum(:compoffs)
  end



end

app/controllers/admin/leave_requests_controller.rb
class Admin::LeaveRequestsController < AdminController
before_filter :authorize

  def index
    @page_title='Leaves'
    if params[:status_search].present? && params[:status_search]=='All'     
      @search=" employee_id>0 "
      @search_heading='';    
    elsif params[:status_search].present?     
      @search="status =  '#{params[:status_search]}'"
      @search_heading=params[:status_search];
    else
      @search = "status = 'Approved'"
      @search_heading='Approved'
    end   
     if params[:fromdate].present?  and  params[:todate]==''
       @search+=" AND fromdate >= '#{Date.parse(params[:fromdate])}'"
     end

     if params[:fromdate]==''  and  params[:todate].present?
       @search+=" AND todate >= '#{Date.parse(params[:todate])}'"
     end

     if params[:fromdate].present? and    params[:todate].present?
       @search+=" AND ((fromdate BETWEEN '#{Date.parse(params[:fromdate])}' AND '#{Date.parse(params[:todate])}') OR (todate BETWEEN '#{Date.parse(params[:fromdate])}' AND '#{Date.parse(params[:todate])}'))"
     end
     if params[:id].present?
      @search+=" AND employee_id >= '#{params[:id]}'"
     end
     if session[:roles].include?(4) == false
      @search+=" AND location_id >= '#{session[:location_id]}'"
     end
    
  #@leave_requests=LeaveRequest.joins(:employee).select('leave_requests.*,(select sum(els) From processed_leaves Where  leave_requests.id=processed_leaves.leave_request_id) as els  ,(select sum(nels) From processed_leaves Where  leave_requests.id=processed_leaves.leave_request_id) as nels ,(select sum(lops) From processed_leaves Where  leave_requests.id=processed_leaves.leave_request_id) as lops,(select sum(compoffs) From processed_leaves Where  leave_requests.id=processed_leaves.leave_request_id) as compoffs').where(@search).paginate(:page => params[:page],:per_page => 10).order("fromdate DESC")
    @leave_requests=LeaveRequest.joins(:employee).where(@search).paginate(:page => params[:page],:per_page => 10).order("fromdate DESC")


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leave_requests }
    end
  end


  # GET /leave_requests/1
  # GET /leave_requests/1.json
=begin
  def show
    @leave_request = LeaveRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leave_request }
    end
   end
=end


  # GET /leave_requests/new
  # GET /leave_requests/new.json
  def new
    @employees=Employee.find(session[:user_id]);
    @leave_request = LeaveRequest.new    
    @manager_list=Employee.joins(:employee_roles).where('employees_roles.role_id=3');
    @options='';
    @manager_list.each do |manager| 
    @options+="[#{manager.id}, #{manager.first_name+'  '+manager.last_name}],"   
    end 
      


    if params[:contactno]=''
      @leave_request.contactno =@employees.contact_no;
    end
    if   params[:address] =''
      @leave_request.address =@employees.address;
    end


    respond_to do |format|
      format.html # manager.html.erb
      format.json { render json: @leave_request }
    end
  end

  # GET /leave_requests/1/edit
  def edit
    @page_title='Employee Leave Edit'
    #@employees = Employee.find(params[:id])
    @leave_request = LeaveRequest.find(params[:id])
    @employees = Employee.find(@leave_request.employee_id)
    @manager_list=Employee.joins(:employee_roles).where('employees_roles.role_id=3');
    @employee_m=employee_module(@leave_request.employee_id);
   
  end

  # POST /leave_requests
  # POST /leave_requests.json
  def create

    @leave_request = LeaveRequest.new(params[:leave_request])
    @leave_request.status = "Pending";
    @leave_request.managerid = params[:manager_id];

    respond_to do |format|
      if @leave_request.save

        @employees = Employee.find(session[:user_id])
        @manager = Employee.find(params[:manager_id])
        UserMailer.welcome_email(@manager,@leave_request,@employees,'Request For Leave',@manager.email).deliver

        format.html { redirect_to request_success_url, notice: 'Leave request  has been sent successfully to your reporting manager' }
        format.json { render json: @leave_request, status: :created, location: @leave_request }

      else
        format.html { render action: "new" }
        format.json { render json: @leave_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leave_requests/1
  # PUT /leave_requests/1.json
  def update
    @leave_request = LeaveRequest.find(params[:id])

    respond_to do |format|
      if @leave_request.update_attributes(params[:leave_request])
         
        @employees = Employee.find(@leave_request.employee_id)
        @manager = Employee.find(@leave_request.managerid)
        if @employees.location_id == 1
        @hr = Employee.find(7)
        elsif @employees.location_id == 2
        @hr = Employee.find(8)
        else
        @hr = Employee.find(3)
        end

        UserMailer.welcome_email(@manager,@leave_request,@employees,'Updated Leave Details By Admin',@employees.email).deliver
        UserMailer.welcome_email(@manager,@leave_request,@employees,'Updated Leave Details By Admin',@manager.email).deliver
        UserMailer.welcome_email(@manager,@leave_request,@employees,'Updated Leave Details By Admin',@hr.email).deliver
        format.html { redirect_to admin_leave_requests_url, notice: 'Leave request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leave_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leave_requests/1
  # DELETE /leave_requests/1.json
=begin
  def destroy
    @leave_request = LeaveRequest.find(params[:id])
    @leave_request.destroy

    respond_to do |format|
      format.html { redirect_to leave_requests_url }
      format.json { head :no_content }
    end
  end
=end

  def request_success

  end

  def request_update

  end

  def employee_leaves
     @search_pending="status = 'Pending'"
     @search_aproved="status = 'Approved'"

     @search=""
     @search+=" ANd "
     @search+= "managerid = #{session[:user_id]}"

    if params[:empid].present?
      @search+=" AND empid LIKE '%#{params[:empid]}%'"
    end
    if params[:first_name].present?
      @search+=" AND first_name LIKE '%#{params[:first_name]}%'"
    end

     if params[:fromdate].present?  and  params[:todate]==''
       @search+=" AND fromdate >= '#{Date.parse(params[:fromdate])}'"
     end

     if params[:fromdate]==''  and  params[:todate].present?
       @search+=" AND todate >= '#{Date.parse(params[:todate])}'"
     end

     if params[:fromdate].present? and    params[:todate].present?
       @search+=" AND ((fromdate BETWEEN '#{Date.parse(params[:fromdate])}' AND '#{Date.parse(params[:todate])}') OR (todate BETWEEN '#{Date.parse(params[:fromdate])}' AND '#{Date.parse(params[:todate])}'))"
     end

     @search_aproved+=" AND fromdate >= '#{Time.now.to_date}'"

     @search_pending+=@search

     @search_aproved+=@search



    @leave_requests_pending = LeaveRequest.joins(:employee).where(@search_pending).paginate(:page => params[:page],:per_page => 10).order("fromdate DESC")
    @leave_requests_approve = LeaveRequest.joins(:employee).where(@search_aproved).paginate(:page => params[:page],:per_page => 10).order("fromdate DESC")

  end

  def leave_cancel
    @leave_request = LeaveRequest.find(params[:id])
    @leave_request.status = "Cancelled";
   
    if params[:path] == "1"
    @cus_request_path=admin_applied_leaves_path(:id=>@leave_request.employee_id,:status_search=>params[:status_search],:path=>'1')
    elsif params[:path] == "2"
    @cus_request_path=admin_leave_requests_path(:status_search=>params[:status_search],:fromdate=>params[:fromdate],:todate=>params[:todate],:path=>'2')
    end

    respond_to do |format|
      if @leave_request.update_attributes(params[:leave_request])

        @employees = Employee.find(@leave_request.employee_id)
        @manager = Employee.find(@leave_request.managerid)
        if @employees.location_id == 1
        @hr = Employee.find(7)
        elsif @employees.location_id == 2
        @hr = Employee.find(8)
        else
        @hr = Employee.find(3)
        end

        UserMailer.welcome_email(@manager,@leave_request,@employees,'Updated Leave Details By Admin', @employees.email).deliver
        UserMailer.welcome_email(@manager,@leave_request,@employees,'Updated Leave Details By Admin', @manager.email).deliver
        UserMailer.welcome_email(@manager,@leave_request,@employees,'Updated Leave Details By Admin',@hr.email).deliver
        
        format.html { redirect_to @cus_request_path, notice: 'Leave request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "leave_requests_path" }
        format.json { render json: @cus_request_path.errors, status: :unprocessable_entity }
      end
    end

  end


  def leave_approve
    @leave_request = LeaveRequest.find(params[:id])
    @leave_employee= @leave_request.employee

  end

  def leave_approve_update

    @leave_request = LeaveRequest.find(params[:id])
    @leave_request.fromdate= params[:fromdate]
    @leave_request.todate= params[:todate]
    @leave_request.status= params[:status]
    @leave_request.resumeon= params[:resumeon]
    @leave_request.numdays= params[:numdays]
    @leave_request.remarks= params[:remarks]



    respond_to do |format|
      if @leave_request.update_attributes(params[:leave_request])
        @employees = Employee.find(params[:employee_id])
        @manager = Employee.find(@employees.manager_id)
         if @employees.location_id == 1
        @hr = Employee.find(7)
        elsif @employees.location_id == 2
        @hr = Employee.find(8)
        else
        @hr = Employee.find(3)
        end

app/helpers/admin/leave_requests_helper.rb
module Admin::LeaveRequestsHelper
end

app/helpers/leave_requests_helper.rb
module LeaveRequestsHelper
end

app/views/leave_requests/edit.html.erb
<%= render 'form' %>

app/views/leave_requests/employee_leaves.html.erb
<section id="body">
  <div class="container">

    <%= form_tag employee_leaves_path,:id=>'search_employee', :name=>'search_employee',:method => :get do %>
        <table class="table2 width_auto" align="center">
          <tr><td align="center"><h1>Search Employee Leaves</h1></td></tr>
          <tr>
            <td>
              <div class="search">
                <%= label_tag :empid, 'By Emp ID:' %>
                <%= text_field_tag :empid, params[:empid] %>
              </div>
              <div class="search">
                <%= label_tag :first_name, 'Name:' %>
                <%= text_field_tag :first_name, params[:first_name] %>
              </div>
            </td>
          </tr>
          <tr>
            <td valign="middle">
              <div class="search">
                <%= label_tag :Fromdate, 'From:' %>
                <%= text_field_tag :fromdate, params[:fromdate],readonly: true%>
                <a href="javascript:void(0)" onclick="if(self.gfPop)gfPop.fStartPop(document.search_employee.fromdate,document.search_employee.todate);return false;" style="text-decoration:none;" ><img class="PopcalTrigger" align="absmiddle" src="/assets/daterange/calendar.png"  border="0" alt="Calendar" onclick="hide();"  width="20"/></a>

              </div>
              <div class="search">
                <%= label_tag :Todate, 'To:' %>
                <%= text_field_tag :todate, params[:todate],readonly: true %>
                <a href="javascript:void(0)" onclick="if(self.gfPop)gfPop.fEndPop(document.search_employee.fromdate,document.search_employee.todate);return false;" style="text-decoration:none;" ><img class="PopcalTrigger" align="absmiddle" src="/assets/daterange/calendar.png"  border="0" alt="Calendar" onclick="hide();"  width="20"/></a>
                </div>

          </tr>
          <tr>
          <td align="center">
            <%= submit_tag "Submit",:class => "button" %>
            <%= button_tag 'Reset', :type => 'reset',:class => "button" %>

          </td>
        </tr>


         </table>
        <iframe width=132 height=142 name="gToday:contrast:agenda.js" id="gToday:contrast:agenda.js" src="/assets/daterange/ipopeng.htm" scrolling="no" frameborder="0" style="visibility:visible; z-index:999; position:absolute; top:-500px; left:-500px;"></iframe>

  <% end %>


    <h2>Pending Requests</h2>
    <table class="table1 width_full">
      <tbody><tr>
        <th class="tabTitle"><strong>S.No.</strong></th>
        <th class="tabTitle"><strong>Emp Id</strong></th>
        <th class="tabTitle"><strong>Name</strong></th>
        <th class="tabTitle"><strong>Leave From</strong></th>
        <th class="tabTitle"><strong>Leave To</strong></th>
        <th class="tabTitle"><strong>No. of Working Days</strong></th>
        <th class="tabTitle"><strong>Resume on</strong></th>
        <th class="tabTitle"><strong>Status</strong></th>
        <th class="tabTitle"><strong>View / Edit / Approve</strong></th>
      </tr>
      <% i = 1 %>
      <% @leave_requests_pending.each do |leave_request_pending| %>
          <tr>
            <td height="25"><%= i %></td>
            <td><%= leave_request_pending.employee.empid.capitalize %></td>
            <td><%= leave_request_pending.employee.first_name.capitalize %></td>
            <td><%= leave_request_pending.fromdate.strftime("%d-%m-%Y") %></td>
            <td><%= leave_request_pending.todate.strftime("%d-%m-%Y") %></td>
            <td><%= leave_request_pending.numdays %></td>
            <td><%= leave_request_pending.resumeon.strftime("%d-%m-%Y") %></td>
            <td>Pending</td>
            <td><%= link_to "View / Edit / Approve",leave_approve_path(:id=>leave_request_pending),:class=>'button' %></td>
          </tr>
          <% i += 1 %>
      <% end %>

<% if @leave_requests_pending.empty? %>
          <tr>
            <td colspan="9" align="center">No Records Found</td>
          </tr>
      <% else %>
              <tr>
                <td colspan="9" align="center">
                  <%= will_paginate @leave_requests_pending, renderer: BootstrapPagination::Rails %>
                  <%= page_entries_info @leave_requests_pending %>

                </td>
              </tr>
      <% end %>


     


      </tbody></table>
    <h2>Employees on Leave</h2>
    <table class="table1 width_full">
      <tbody><tr>
        <th class="tabTitle"><strong>S.No.</strong></th>
        <th class="tabTitle"><strong>Emp Id</strong></th>
        <th class="tabTitle"><strong>Name</strong></th>
        <th class="tabTitle"><strong>Leave From</strong></th>
        <th class="tabTitle"><strong>Leave To</strong></th>
        <th class="tabTitle"><strong>No. of Working Days</strong></th>
        <th class="tabTitle"><strong>Resume on</strong></th>
        <th class="tabTitle"><strong>Contact No</strong></th>
        <th class="tabTitle"><strong>Edit / Cancel</strong></th>
      </tr>
      <% z = 1 %>
      <% @leave_requests_approve.each do |leave_request_approve| %>

          <tr>
            <td height="25"><%= z %></td>
            <td><%= leave_request_approve.employee.empid.capitalize %><%= @leave_requests_approve.count %></td>
            <td><%= leave_request_approve.employee.first_name.capitalize %></td>
            <td><%= leave_request_approve.fromdate.strftime("%d-%m-%Y") %></td>
            <td><%= leave_request_approve.todate.strftime("%d-%m-%Y") %></td>
            <td><%= leave_request_approve.numdays %></td>
            <td><%= leave_request_approve.resumeon.strftime("%d-%m-%Y") %></td>
            <td><%= leave_request_approve.employee.contact_no %><%= @leave_requests_pending.count-1 %></td>
            <td><%= link_to "Edit / Cancel",leave_approve_path(:id=>leave_request_approve),:class=>'button' %></td>
          </tr>
          <% z += 1 %>
      <% end %>
     
         <%  if @leave_requests_approve.count>10 %>
                <tr>
                  <td colspan="9" align="center">
                    <%= will_paginate @leave_requests_approve, renderer: BootstrapPagination::Rails %>
                    <%= page_entries_info @leave_requests_approve %>
                  </td>
                </tr>
                <% end %>
                <% if @leave_requests_approve.empty? %>
                <tr>
                  <td colspan="9" align="center">No Records Found</td>
                </tr>
                <% end %>


      


      </tbody></table>

  </div>
</section>

app/views/leave_requests/index.html.erb
<section id="body">
  <div class="container">
    <div class="col12">
      <%= form_tag leave_requests_path, :method => :get do %>

          <table class="width_full" style="border:solid 1px #0d5478;">
            <tr>
              <td colspan="7">
                <table width="100%" >
                  <tr>
                    <td>  <h2><%= params[:status_search] || 'Approved' %> Leaves <% if @leave_requests.count!=0 %>(<%= @leave_requests.count %>)<% end %></h2>
                    </td>
                    <td align="right">
                      <%= select_tag(:status_search, options_for_select([['All', 'All'],['Pending', 'Pending'], ['Approved', 'Approved'],['Rejected', 'Rejected'], ['Cancelled', 'Cancelled'], ['Commited', 'Commited']], params[:status_search] || 'Approved'),:onchange => 'this.form.submit()') %>
                    </td>
                  </tr>
                </table>
      <% end %>
      </td>
      </tr>
          <tr>
            <td colspan="2">
              <table class="table1 width_full">
                <tbody><tr>
                  <th class="tabTitle"><strong>S.No.</strong></th>
                  <th class="tabTitle"><strong>From</strong></th>
                  <th class="tabTitle"><strong>To</strong></th>
                  <th class="tabTitle"><strong>No. of Working Days</strong></th>
                  <th class="tabTitle"><strong>Type of Leaves</strong></th>
                  <th class="tabTitle"><strong>Status</strong></th>
                  <th class="tabTitle" style="padding-left:20px; padding-right:20px"><strong>Options</strong></th>
                </tr>
                <% i=1 %>
                <% @leave_requests.each do |leave_request| %>
                <tr>
                  <td><%= i %></td>
                  <td><%= leave_request.fromdate.strftime("%d-%m-%Y") %></td>
                  <td><%= leave_request.todate.strftime("%d-%m-%Y") %></td>
                  <td><%= leave_request.numdays %></td>
                  <td>
                  <% if leave_request.processed_leave.els_count==0 &&  leave_request.processed_leave.nels_count==0 && leave_request.processed_leave.lops_count==0 && leave_request.processed_leave.compoffs_count==0 %>--
                  <% else %>
                  <% if  leave_request.processed_leave.els_count!=0 || leave_request.processed_leave.els_count!=0.0 %>
                  ELs <%= number_to_human(leave_request.processed_leave.els_count) %>
                  <% end %> 
                  <% if leave_request.processed_leave.nels_count!=0 || leave_request.processed_leave.nels_count!=0.0 %>
                  NEls <%= number_to_human(leave_request.processed_leave.nels_count) %>
                  <% end %> 
                  <% if  leave_request.processed_leave.lops_count!=0 || leave_request.processed_leave.lops_count!=0.0 %>
                  Lops <%= number_to_human(leave_request.processed_leave.lops_count) %>
                  <% end %> 
                  <% if  leave_request.processed_leave.compoffs_count!=0 || leave_request.processed_leave.compoffs_count!=0.0 %>
                  Compoffs <%= number_to_human(leave_request.processed_leave.compoffs_count) %>
                  <% end %> 
                  <% end %>  
                  </td>
                  <td><%= leave_request.status %></td>
                  <td align="center">
                    <% if Date.today<=leave_request.todate == true and  leave_request.status!='Cancelled' and  leave_request.status!='Rejected' and  leave_request.status!='Commited' and  leave_request.status!='Pending'  and  leave_request.status=='Approved' %>
                    <a onClick="return confirm('Please contact your reporting manager to edit this leave.');"><%= image_tag("view_edit.png", alt: "View/Edit" , title:"View/Edit") %></a>
                    <% end %>

                    <% if Date.today<=leave_request.todate == true and  leave_request.status=='Pending' %>
                        <a href="<%= edit_leave_request_path(leave_request) %>" ><%= image_tag("view_edit.png", alt: "View/Edit" , title:"View/Edit") %></a>
                    <% end %>
                    <% if Date.today<=leave_request.todate == true and  (leave_request.status=='Approved' || leave_request.status=='Pending') %>
                    <% if leave_request.status=='Approved' %>
                    <%= link_to (image_tag "cancel.png", :title => 'Cancel'),'#',:confirm => "Please contact your reporting manager to cancel this leave."  %>
                    <% else  %>
   <%= link_to (image_tag "cancel.png", :title => 'Cancel'),leave_cancel_path(:id=>leave_request),:confirm => "Are you sure u want to cancel this leave?"  %>
                    <% end %>

                    <% end %>


                  </td>
                </tr>
                <% i+=1 %>
                <% end %>
                <%  if @leave_requests.count>10 %>
                <tr>
                  <td colspan="7" align="center">
                    <%= will_paginate @leave_requests, renderer: BootstrapPagination::Rails %>
                    <%= page_entries_info @leave_requests %>
                  </td>
                </tr>
                <% end %>
                <% if @leave_requests.empty? %>
                <tr>
                  <td colspan="7" align="center">No Records Found</td>
                </tr>
                <% end %>


                </tbody></table>
            </td>
          </tr>
        </table>


    </div>
  </div>

</section>

app/views/leave_requests/new.html.erb
<%= render 'form' %>

app/views/leave_requests/request_success.html.erb
<section id="body">
  <div class="container">
    <div class="col12">
      <table class="table2 width_full" style="border:solid 1px #0d5478;">
        <tr>
          <td>
            <table align="center">
              <tr><td colspan="2" align="center"><h1>Leave request  has been sent successfully to your reporting manager</h1></td></tr>
            </table>
          </td>
        </tr>
      </table>
    </div>
  </div>
</section>

app/views/leave_requests/request_update.html.erb
<section id="body">
  <div class="container">
    <div class="col12">
      <table class="table2 width_full" style="border:solid 1px #0d5478;">
        <tr>
          <td>
            <table align="center">
              <tr><td colspan="2" align="center"><h1>Leave request was successfully updated</h1></td></tr>
            </table>
          </td>
        </tr>
      </table>
    </div>
  </div>
</section>

app/views/leave_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Employee:</b>
  <%= @leave_request.employee_id %>
</p>

<p>
  <b>Fromdate:</b>
  <%= @leave_request.fromdate %>
</p>

<p>
  <b>Todate:</b>
  <%= @leave_request.todate %>
</p>

<p>
  <b>Numdays:</b>
  <%= @leave_request.numdays %>
</p>

<p>
  <b>Resumeon:</b>
  <%= @leave_request.resumeon %>
</p>

<p>
  <b>Reason:</b>
  <%= @leave_request.reason %>
</p>

<p>
  <b>Contactno:</b>
  <%= @leave_request.contactno %>
</p>

<p>
  <b>Address:</b>
  <%= @leave_request.address %>
</p>

<p>
  <b>Currentproject:</b>
  <%= @leave_request.currentproject %>
</p>

<p>
  <b>Managerid:</b>
  <%= @leave_request.managerid %>
</p>

<p>
  <b>Remarks:</b>
  <%= @leave_request.remarks %>
</p>

<p>
  <b>Createdby:</b>
  <%= @leave_request.createdby %>
</p>

<p>
  <b>Modifiedby:</b>
  <%= @leave_request.modifiedby %>
</p>


<%= link_to 'Edit', edit_leave_request_path(@leave_request) %> |
<%= link_to 'Back', leave_requests_path %>