config/routes.rb
Leave::Application.routes.draw do

  resources :roles

  resources :admin, :only => [:index], :controller => :admin
  namespace :admin do   
  resources :employees do
   collection do
        get 'search'
        get 'export_to_csv' => :export_to_csv 
        
      end   
  end
  resources :locations
  resources :leave_requests
  resources :leaves
controller :leave_requests do
    get 'request_leave' => :new
    get 'request_success' => :request_success
    get 'leave_request_search' =>:index
    get 'request_update' =>   :request_update
    get 'employee_leaves' =>   :index
    get 'applied_leaves' =>   :applied_leaves
    get 'leave_cancel' =>   :leave_cancel
    get 'leave_approve' =>   :leave_approve
    post 'leave_approve_update' =>   :leave_approve_update
    get 'commit_leave' =>   :commit_leave
    post 'leave_request_commit' =>   :leave_request_commit
    get 'forcedleave' =>   :forcedleave
    get 'addforcedleave' =>   :addforcedleave
    post 'addforcedleave' =>   :addforcedleave
  

    

  end

  resources :high_scores    
  end

  resources :leaves
  resources :employees 
  resources :leave_requests
 
  get 'change_password' => 'sessions#change_password'
  post 'change_update' => 'sessions#change_update'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  controller :leave_requests do
    get 'request_leave' => :new
    get 'request_success' => :request_success
    get 'leave_request_search' =>:index
    get 'request_update' =>   :request_update
    get 'employee_leaves' =>   :employee_leaves
    get 'leave_cancel' =>   :leave_cancel
    get 'leave_approve' =>   :leave_approve
    post 'leave_approve_update' =>   :leave_approve_update

  end

  root :to => 'sessions#new'

end

app/views/layouts/_employee_module.html.erb
 <table class="table1" width="85%">
          <tr><th colspan="2" class="tabTitle">Available Leaves upto 1st of current month</th></tr>
		  <tr><td>ELs:</td><td><%= @employee_m.els %></td></tr><tr><td>NELs:</td><td><%= @employee_m.nels %></td></tr><tr><td colspan="2"><em>Number of leaves applied/taken from 1st of current month: <%= number_to_human(@employee_m.lops) %> days.</em></td></tr></table>                </td></tr>
        </table>

app/views/layouts/_footer.html.erb
<div style="clear:both; height:20px;"></div>
<footer>
  <p>All Rights Reserved Logictree IT Solutions Inc. 2013</p>
</footer>
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= @page_title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

</head>
<body>
<header>
  <div class="container">

    <h1 id="logo" style="margin:0 auto; float:none; width:199px; margin-top:50px;"><%= link_to "", root_path %></h1>
  </div>
</header>

app/views/layouts/_header_admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Admin - <%= @page_title %></title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js" %>



  <![endif]-->

</head>
<body>
<header>
  <div class="container">
    <section class="userdetails">
	<span class="fleft"><strong><%= session[:first_name].capitalize %> <%= session[:last_name].capitalize %> - <%= session[:user_empid] %></strong></span>
       <%= link_to 'Sign Out', logout_path, method: :delete, :class => "button fright" %></section>
  	<h1 id="logo"><%= link_to "", admin_employees_path%></h1>
  </div>
  <nav class="clearfix">
  	<div class="container">
        <ul id="menu" class="clearfix">
            <li  <% if (controller.controller_name=='employees' || (controller.controller_name=='leave_requests' && controller.action_name !='index'  && controller.action_name !='edit') || controller.controller_name=='leaves' ) and  (controller.action_name =='index' || controller.action_name =='edit' || controller.action_name =='applied_leaves' || params[:path]=='1') %> class='active'<% end %>><%= link_to 'Employees' ,admin_employees_path %><% controller.controller_name %><% controller.action_name %></li>
            <li <% if controller.controller_name=='leave_requests' and  (controller.action_name =='index' || controller.action_name =='edit' ||  params[:path]=='2') %> class='active'<% end %>><%= link_to 'Leaves' ,admin_leave_requests_path %></li>
            <li <% if controller.controller_name=='leave_requests' and  (controller.action_name =='forcedleave') %> class='active'<% end %>><%= link_to 'Forced Leaves' ,admin_forcedleave_path %></li>           
        </ul>
        <a href="#" id="pull"><span>Menu</span></a>
    </div>
  </nav>
</header>

app/views/layouts/_header_session.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Employee - <%= @page_title %></title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js" %>



  <![endif]-->

</head>
<body>
<header>
  <div class="container">
    <section class="userdetails">
	<span class="fleft"><strong><%= session[:first_name].capitalize %> <%= session[:last_name].capitalize %> - <%= session[:user_empid] %></strong></span>
       <%= link_to 'Sign Out', logout_path, method: :delete, :class => "button fright" %></section>
  	<h1 id="logo"><%= link_to "", root_path%></h1>
  </div>
  <nav class="clearfix">
  	<div class="container">
        <ul id="menu" class="clearfix">
            <li <% if controller.controller_name=='leave_requests' and  (controller.action_name =='new') %> class='active'<% end %> ><%= link_to 'Request for Leave' ,request_leave_path %></li>
            <li <% if controller.controller_name=='leave_requests' and  (controller.action_name =='index' || controller.action_name =='leave_cancel' || controller.action_name =='edit')%> class='active'<% end %>><%= link_to 'Applied Leaves' ,leave_requests_path %></li>
	    <% if session[:roles].include?(3)  %>
	    <li <% if controller.controller_name=='leave_requests' and  (controller.action_name =='employee_leaves' || controller.action_name =='leave_approve') %> class='active'<% end %>><%= link_to "Employee's Leaves" ,employee_leaves_path %></li>
	   <%  end %> 
            <li <% if controller.controller_name=='sessions' and  controller.action_name =='change_password' %> class='active'<% end %>><%= link_to "Change Password",change_password_path %></li>
        </ul>
        <a href="#" id="pull"><span>Menu</span></a>
    </div>
  </nav>
</header>

app/views/layouts/admin.html.erb
<%= render 'layouts/header_admin' %>
<%= yield %>
<%= render 'layouts/footer' %>

app/views/layouts/application.html.erb
<% if session[:user_id] %>
<%= render 'layouts/header_session' %>
<% else %>

<%= render 'layouts/header' %>
<% end %>
<%= yield %>
<% if session[:user_id] %>
<%= render 'layouts/footer' %>
<% end %>